Importing the Packages


In [646]:
import numpy as np

In [647]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

Importing the Data

In [648]:
data = np.genfromtxt('loan-data.csv', delimiter=';',
                     skip_header=1, autostrip=True)
data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Checking for incomplete data

In [649]:
np.isnan(data).sum()

88005

In [650]:
temperory_fill = np.nanmax(data) + 1
temperory_mean = np.nanmean(data, axis=0)

<ipython-input-650-a4573aee14fb>:2: RuntimeWarning: Mean of empty slice
  temperory_mean = np.nanmean(data, axis=0)


In [651]:
temperory_fill

68616520.0

In [652]:
temperory_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [653]:
temperory_stats = np.array([np.nanmin(data, axis=0),
                           temperory_mean,
                           np.nanmax(data, axis=0)])

<ipython-input-653-d14ddd6dd982>:1: RuntimeWarning: All-NaN slice encountered
  temperory_stats = np.array([np.nanmin(data, axis=0),
<ipython-input-653-d14ddd6dd982>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(data, axis=0)])


In [654]:
temperory_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

Splitting the Dataset

In [655]:
column_strings = np.argwhere(np.isnan(temperory_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [656]:
column_numeric = np.argwhere(np.isnan(temperory_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

Reimporting the Dataset and splitting it into 2 smaller arrays

In [657]:
# The string dataset
data_strings = np.genfromtxt('loan-data.csv', delimiter=';',
                             skip_header=1, autostrip=True, usecols=column_strings, dtype=str)
data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [658]:
# The numeric dataset
data_numeric = np.genfromtxt('loan-data.csv', delimiter=';', skip_header=1,
                             autostrip=True, usecols=column_numeric, filling_values=temperory_fill)
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Name of the Columns

In [659]:
header_full = np.genfromtxt('loan-data.csv', delimiter=';',
                            autostrip=True,skip_footer=data.shape[0], dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [660]:
header_strings,header_numeric = header_full[column_strings],header_full[column_numeric]

In [661]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [662]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

Creating Checkpoints

In [663]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header = checkpoint_header,data = checkpoint_data)
    checkpoint_variable = np.load(file_name+".npz")
    return(checkpoint_variable)

In [664]:
checkpoint_test = checkpoint("checkpoint_test",header_strings,data_strings)

In [665]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [666]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [667]:
np.array_equal(checkpoint_test['data'],data_strings)

True

Manipulating String Columns

In [668]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [669]:
header_strings[0]= 'issue_date'

In [670]:
data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

Issue Date

In [671]:
np.unique(data_strings[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [672]:
data_strings[:, 0] = np.chararray.strip(data_strings[:, 0], "-15")

In [673]:
np.unique(data_strings[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [674]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [675]:
for i in range(13):
    data_strings[:, 0] = np.where(data_strings[:, 0] == months[i],
                                  i,
                                  data_strings[:, 0])

In [676]:
np.unique(data_strings[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

Loan Status

In [677]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [678]:
np.unique(data_strings[:, 1])
#Here the data are catergorized as
#good(Current/Fully Paid/In Grace Period/Issued/Late (16-30 days)-->short period latency is safe)<--->1
#bad(''/Charged Off/Default/Late (31-120 days)-->long period latency is unsafe)<--->0

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [679]:
np.unique(data_strings[:, 1]).size

9

In [680]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [681]:
data_strings[:, 1] = np.where(np.isin(data_strings[:, 1], status_bad), 0, 1)

In [682]:
np.unique(data_strings[:, 1])

array(['0', '1'], dtype='<U69')

Term

In [683]:
np.unique(data_strings[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [684]:
data_strings[:, 2] = np.chararray.strip(data_strings[:, 2], " months")
data_strings[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [685]:
header_strings[2] = 'term_months'

In [686]:
data_strings[:, 2] = np.where(data_strings[:, 2] == '',
                              '60',
                              data_strings[:, 2])

In [687]:
np.unique(data_strings[:,2]) #Since there is significance to the value, then it is not converted as 0 and 1

array(['36', '60'], dtype='<U69')

Grade and Subgrade

In [688]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [689]:
np.unique(data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [690]:
np.unique(data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Filling sub grade

In [691]:
# The empty space has the id 0 and hence we are selecting from the id 1 and so on
for i in np.unique(data_strings[:, 3])[1:]:
    data_strings[:, 4] = np.where((data_strings[:, 4] == '') & (data_strings[:, 3] == i),
                                  i+"5",
                                  data_strings[:, 4])

In [692]:
np.unique(data_strings[:, 4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [693]:
# Since there is only 9 missing values,we could drop the values
#We can assign a new grade for the missing value instead of dropping the values
data_strings[:, 4] = np.where(data_strings[:, 4] == '',
                              'H1',
                              data_strings[:, 4])

In [694]:
np.unique(data_strings[:, 4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Removing Grade

In [695]:
# Since the information contained in the grade is now carried in subgrade,we can drop the grade coloumn
data_strings = np.delete(data_strings, 3, axis=1)

In [696]:
data_strings[:, 3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [697]:
header_strings = np.delete(header_strings, 3)

In [698]:
header_strings[3]

'sub_grade'

Converting sub grade

In [699]:
np.unique(data_strings[:, 3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [700]:
keys = list(np.unique(data_strings[:, 3]))
values = list(range(1, np.unique(data_strings[:, 3]).shape[0]+1))
dict_sub_grade = dict(zip(keys, values))

In [701]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [702]:
for i in np.unique(data_strings[:, 3]):
    data_strings[:, 3] = np.where(data_strings[:, 3] == i,
                                  dict_sub_grade[i],
                                  data_strings[:, 3])

In [703]:
np.unique(data_strings[:, 3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

Verification Status

In [704]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [705]:
np.unique(data_strings[:, 4])
# Here the data are catergorized as
# good(Source Verified/Verified)<--->1
# bad(''/Not Verified)<--->0

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [706]:
data_strings[:, 4] = np.where((data_strings[:, 4] == '') | (
    data_strings[:, 4] == 'Not Verified'), 0, 1)

In [707]:
np.unique(data_strings[:, 4])

array(['0', '1'], dtype='<U69')

URL

In [708]:
np.unique(data_strings[:, 5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [709]:
data_strings[:, 5] = np.chararray.strip(
    data_strings[:, 5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [710]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [711]:
data_numeric[:, 0].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [712]:
data_strings[:, 5].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [713]:
np.array_equal(data_numeric[:, 0].astype(dtype=int),
               data_strings[:, 5].astype(dtype=int))

True

In [714]:
# Since the id and the url details are the same, we can drop the url column
data_strings = np.delete(data_strings, 5, axis=1)
header_strings = np.delete(header_strings, 5)

In [715]:
data_strings[:, 5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [716]:
data_numeric[:, 0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

State Addresses

In [717]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [718]:
header_strings[5] = 'state_address'

In [719]:
np.unique(data_strings[:, 5]).size

50

In [720]:
states_name, states_count = np.unique(data_strings[:, 5], return_counts=True)
# The missing state is 'Iowa'
states_count_sorted = np.argsort(-states_count)
states_name[states_count_sorted], states_count[states_count_sorted]
# Most of the accounts come from the populated and wealthy states
# Only 4 states have higher data than the missing value ''
# hence there are more application with missing or unreported address than the next 45 states
# We have very little data for too many states to examine each one individually
# If we assign a unique value to each state,this will cause outliers to have high influence on the coefficient for less represented states
# The more categories a variable has, the fewer data will be available for each one
# Therefore the states with fewer applications will be more vulnerable to have the coefficents affected by outliers

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [721]:
# instead of '',it is replaced with 0
# accounts which cannot be attributed to a specific state wont be included in any region to avoid biasing with variable coefficient
data_strings[:, 5] = np.where(data_strings[:, 5] == '',
                              0,
                              data_strings[:, 5])

In [722]:
# To solve the problem,the states are grouped based on certain common characterstics
# Hence the states are grouped geographically
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID',
                       'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN',
                        'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(
    ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [723]:
data_strings[:, 5] = np.where(
    np.isin(data_strings[:, 5], states_west), 1, data_strings[:, 5])
data_strings[:, 5] = np.where(
    np.isin(data_strings[:, 5], states_south), 2, data_strings[:, 5])
data_strings[:, 5] = np.where(
    np.isin(data_strings[:, 5], states_midwest), 3, data_strings[:, 5])
data_strings[:, 5] = np.where(
    np.isin(data_strings[:, 5], states_east), 4, data_strings[:, 5])

In [724]:
np.unique(data_strings[:, 5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

Converting to Numbers

In [725]:
data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [726]:
data_strings = data_strings.astype(dtype=int)

In [727]:
data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

Checkpoint

In [728]:
checkpoint_strings = checkpoint(
    "checkpoint_strings", header_strings, data_strings)

In [729]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [730]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [731]:
np.array_equal(checkpoint_strings['data'], data_strings)

True

Manipulating Numeric Columns

In [732]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [733]:
np.isnan(data_numeric).sum()
# The fillers must be substituted the fillers with the worst possible values

0

Substitute 'filler' values

In [734]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

ID

In [735]:
temperory_fill

68616520.0

In [736]:
np.isin(data_numeric[:, 0], temperory_fill)

array([False, False, False, ..., False, False, False])

In [737]:
np.isin(data_numeric[:, 0], temperory_fill).sum()

0

In [738]:
header_numeric
# Here minimum value considered worst is the funded amt
# switch out all the fillers for the minimum -->funded_amnt
# switch out all the fillers for the maximum -->loan_amnt,int_rate,installment,total_pymnt

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

Temperory Stats

In [739]:
temperory_stats[:, column_numeric]
# min
# mean
# max

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

Funded amount

In [740]:
# Funded amount filler value must be equal to minimum
data_numeric[:, 2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [741]:
data_numeric[:, 2] = np.where(data_numeric[:, 2] == temperory_fill,
                              temperory_stats[0, column_numeric[2]],
                              data_numeric[:, 2])
data_numeric[:, 2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [742]:
temperory_stats[0, column_numeric[3]]

6.0

Loaded amount,Interest Rate,Total Payment,Installment

In [743]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [744]:
# Funded amount filler value must be equal to maximum
for i in [1, 3, 4, 5]:
    data_numeric[:, i] = np.where(data_numeric[:, i] == temperory_fill,
                                  temperory_stats[2, column_numeric[i]],
                                  data_numeric[:, i])

In [745]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

Currency Change

The Exchange Rate

In [746]:
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter=',',
                        autostrip=True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [747]:
data_strings[:, 0]  # months changed to numeric values

array([ 5,  0,  9, ...,  6,  4, 12])

In [748]:
exchange_rate = data_strings[:, 0]
for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,  # when the issue date was not available,it was assigned with 0
                         # it value is based on the mean of the exchange rates
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [749]:
exchange_rate.shape

(10000,)

In [750]:
data_numeric.shape

(10000, 6)

In [751]:
exchange_rate = np.reshape(exchange_rate, (10000, 1))

In [752]:
data_numeric = np.hstack((data_numeric, exchange_rate))

In [753]:
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [754]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [755]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

From USD to EUR

In [756]:
columns_dollars = np.array([1,2,4,5])

In [758]:
data_numeric[:,(columns_dollars)]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [760]:
for i in columns_dollars:
    data_numeric = np.hstack((data_numeric,np.reshape(data_numeric[:,i]/data_numeric[:,6],(10000,1))))

In [762]:
data_numeric.shape

(10000, 11)

In [764]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

Expanding the Header

In [765]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollars]])

In [766]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [767]:
header_numeric = np.concatenate((header_numeric,header_additional))

In [769]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [770]:
header_numeric[columns_dollars] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollars]])

In [771]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [772]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [774]:
header_numeric = header_numeric[columns_index_order]

In [775]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [777]:
data_numeric = data_numeric[:,columns_index_order]

Interest Rate

In [779]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [780]:
data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [782]:
data_numeric[:,5] = data_numeric[:,5]/100

In [783]:
data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

Checkpoint

In [784]:
checkpoint_numeric = checkpoint('checkpoint_numeric',header_numeric,data_numeric)

In [786]:
checkpoint_numeric['header'],checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

Creating a "Completed" Dataset

In [787]:
checkpoint_strings['data'].shape

(10000, 6)

In [788]:
checkpoint_numeric['data'].shape

(10000, 11)

In [794]:
cleaned_data = np.hstack((checkpoint_numeric['data'],checkpoint_strings['data']))

In [795]:
cleaned_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [797]:
np.isnan(cleaned_data).sum()

0

In [806]:
header_full = np.concatenate((checkpoint_numeric['header'],checkpoint_strings['header']))

In [807]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

Sorting the new dataset

In [808]:
cleaned_data = cleaned_data[np.argsort(cleaned_data[:,0])]

In [809]:
cleaned_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [810]:
np.argsort(cleaned_data[:, 0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

Storing the new dataset

In [812]:
cleaned_data = np.vstack((header_full, cleaned_data))

In [814]:
np.savetxt('data-preprocessed.csv', cleaned_data, fmt='%s', delimiter=',')